include: package:surf_lint_rules/analysis_options.yaml

dart_code_metrics:
  rules:
    - member-ordering:
      order:
        - constructors
        - public-static-const-fields
        - private-static-const-fields
        - public-static-final-fields
        - private-static-final-fields
        - public-static-fields
        - private-static-fields
        - public-final-fields
        - private-final-fields
        - public-fields
        - public-getters-setters
        - private-fields
        - private-getters-setters
        - named-constructors
        - factory-constructors
        - overridden-methods
        - public-static-methods
        - public-methods
        - protected-methods
        - private-static-methods
        - private-methods