name: time_tracker
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  elementary: ^0.1.2
  cupertino_icons: 1.0.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0

dev_dependencies:
  # тестирование elementary
  elementary_test: ^0.1.2
  flutter_test:
    sdk: flutter
  # сериализация json
  json_serializable: ^5.0.2
  # голден тесты
  golden_toolkit: ^0.10.0
  # мокирование
  mocktail: ^0.2.0
  # анализатор
  surf_lint_rules: ^1.4.0

flutter:
  uses-material-design: true