name: time_tracker
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.2
  cupertino_icons: 1.0.4
  dart_code_metrics: ^4.8.1
  elementary: ^0.1.2
  firebase_core: ^1.10.3
  flutter:
    sdk: flutter
  freezed: ^1.0.2+1
  intl: ^0.17.0
  json_serializable: ^6.1.1
  provider: ^6.0.0
  rxdart: ^0.27.3

dev_dependencies:
  # тестирование elementary
  build_runner: ^2.1.5
  elementary_test: ^0.1.2
  flutter_test:
    sdk: flutter
  # голден тесты
  golden_toolkit: ^0.12.0
  # сериализация json
  # мокирование
  mocktail: ^0.2.0
  # анализатор
  surf_lint_rules: ^1.4.0

flutter:
  uses-material-design: true