name: time_tracker
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.4
  elementary: ^0.1.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0
  uuid: ^3.0.5

dev_dependencies:
  # тестирование elementary
  elementary_test: ^0.1.2
  flutter_test:
    sdk: flutter
  # голден тесты
  golden_toolkit: ^0.12.0
  # сериализация json
  json_serializable: ^6.1.1
  # мокирование
  mocktail: ^0.2.0
  # анализатор
  surf_lint_rules: ^1.4.0

flutter:
  uses-material-design: true